[project]
name = "airi-pipelines"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.12"

[dependency-groups]
dev = [
    "basedpyright>=1.38",
    "pytest>=9",
    "ruff>=0.15",
    "toolbox",
]

[tool.uv.workspace]
members = ["toolbox-lib"]

[tool.uv.sources]
toolbox = { workspace = true }

[tool.basedpyright]
pythonVersion = "3.12"
typeCheckingMode = "recommended"
# Don't require return values to be assigned to variables. Common functions like
# `await asyncio.gather()` have non-None return values, but those return values
# often aren't important. This rule can create a lot of noise.
reportUnusedCallResult = false

[tool.ruff]
src = ["toolbox-lib/src"]
target-version = "py312"

[tool.ruff.lint]
select = [
    "A",     # builtin shadowing
    "ARG",   # unused arguments
    "B",     # bugbear
    "C4",    # comprehension flaws
    "DTZ",   # naive datetime usage
    "E",     # pycodestyle errors
    "F",     # pyflakes
    "I",     # isort
    "N",     # pep8-naming
    "PLC",   # pylint convention
    "PLE",   # pylint errors
    "PLW",   # pylint warnings
    "PT",    # pytest style
    "PTH",   # pathlib preference
    "RET",   # return style
    "RUF",   # ruff-specific rules
    "SIM",   # simplify
    "T20",   # print statements
    "UP",    # pyupgrade
    "W",     # pycodestyle warnings
]

[tool.pytest]
addopts = [
    "--import-mode=importlib",
]
strict = true
testpaths = ["toolbox-lib/tests"]
xfail_strict = true
