#!/bin/sh

# pipeline-explorer
if git diff --cached --name-only | grep -q '^pipeline-explorer/'; then
  cd "$(git rev-parse --show-toplevel)/pipeline-explorer" || exit 1

  echo "pipeline-explorer: running eslint..."
  npm run lint || exit 1

  echo "pipeline-explorer: running typecheck..."
  npm run typecheck || exit 1
fi
