name: Python CI

on:
  push:
    branches:
      - main
    paths:
      - "**/*.py"
      - "**/pyproject.toml"
      - "uv.lock"
  pull_request:
    paths:
      - "**/*.py"
      - "**/pyproject.toml"
      - "uv.lock"

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - name: Format
        run: uv run ruff format --check

      - name: Lint
        run: uv run ruff check

      - name: Typecheck
        run: uv run basedpyright

      - name: Test
        run: uv run pytest
